name: boletim-diario
on: push
permissions:
  contents: read
  issues: write
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      
      - name: criar-boletim
        run: |
          # Boletim diario de segurança
          chmod +x ./script.sh 
          ./script.sh

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATA: "01/01/2022"
          CONTEUDO: |
            Teste 1
            Teste 2
        with:
          filename: .github/boletim.md
