name: boletim-diario
on: push
permissions:
  contents: read
  issues: write
jobs:
  boletim-diario:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      
      - name: criar-boletim
        run: |
          # Boletim diario de segurança
          chmod +x ./script.sh 
          ./script.sh
          echo "DATA=$(date +%d-%m-%Y)" >> $GITHUB_OUTPUT
          echo "CONTEUDO=$(cat boletim_final.txt)" >> $GITHUB_OUTPUT

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATA: ${{ steps.criar-boletim.outputs.DATA }}
          CONTEUDO: ${{ steps.criar-boletim.outputs.CONTEUDO }}
        with:
          filename: .github/boletim.md
