name: boletim-diario
on: push
permissions:
  contents: read
  issues: write
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      
      - name: criar-boletim
        run: |
          # Boletim diario de segurança
          chmod +x ./script.sh 
          ./script.sh
          export DATA=$(date +%Y-%m-%d)
          export CONTEUDO=$(cat boletim_final.txt)

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/boletim.md
