name: boletim-diario
on: push
permissions:
  contents: read
  issues: write
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      
      - name: criar-boletim
        run: |
          # Boletim diario de segurança
          chmod +x ./script.sh 
          ./script.sh
