name: boletim-diario
on: 
    schedule:
        - cron: '0 13 * * *'
    
permissions:
  contents: read
  issues: write
jobs:
  boletim-diario:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: criar-boletim
        env:
            GH_TOKEN: ${{ github.token }}
        run: |

          # Boletim diario de segurança
          sudo apt-get update -y
          sudo apt -y install libxml2-utils
          chmod +X ./script.sh
          bash ./script.sh
          
          chmod +X ./number.sh
          bash ./number.sh
          
          echo "SCRIPT_DATA=$(date +'%d/%m/%Y')" >> $GITHUB_ENV
          echo 'SCRIPT_CONTEUDO<<EOF' >> $GITHUB_ENV
          cat boletim_final.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          
          var=$( cat numero_final.txt )
          echo $var
          gh issue close $var
   

      - uses: JasonEtco/create-an-issue@v2
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATA: ${{ env.SCRIPT_DATA }}
        with:
          filename: .github/boletim.md

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.create-issue.outputs.number }}
          reactions: '+1'
          body: |
            ${{ env.SCRIPT_CONTEUDO }}
