name: boletim-diario
on: 
  check_run:
        types: 
            - if: ${{'11:47:00'}} == ${{ env.SCRIPT_HORA }}
            
permissions:
  contents: read
  issues: write
jobs:
  boletim-diario:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: criar-boletim
        run: |

          # Boletim diario de segurança
          sudo apt -y install libxml2-utils
          chmod +X ./script.sh
          bash ./script.sh
          echo "SCRIPT_HORA=$(TZ='America/Sao_Paulo' date +"%T")" >> $GITHUB_ENV
          echo "SCRIPT_DATA=$(date +'%d/%m/%Y')" >> $GITHUB_ENV
          echo 'SCRIPT_CONTEUDO<<EOF' >> $GITHUB_ENV
          cat boletim_final.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - uses: JasonEtco/create-an-issue@v2
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATA: ${{ env.SCRIPT_DATA }}
          HORA: ${{ env.SCRIPT_HORA }}
        with:
          filename: .github/boletim.md

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.create-issue.outputs.number }}
          reactions: '+1'
          body: |
            ${{ env.SCRIPT_CONTEUDO }}
