name: boletim-diario
on: push
permissions:
  contents: read
  issues: write
jobs:
  boletim-diario:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: criar-boletim
        run: |

          # Boletim diario de segurança
          sudo apt -y install libxml2-utils

          # Get Text from 'https://boletimsec.com.br/boletim-diario-ciberseguranca/' to boletim.html file
          curl -s https://boletimsec.com.br/boletim-diario-ciberseguranca/ > boletim1.txt

          # Get element by js path from boletim.html file to boletim.txt file
          xmllint --html --xpath "/html/body/div[1]/main/section[2]/div/div/div[2]/div/div/div[2]" boletim1.txt 1> boletim2.txt 2> /dev/null

          # Format date to dd/mm/yyyy
          DATE=$(date +%d/%m/%Y)

          # Create file and header
          echo "# Boletim de Segurança" > boletim_final.txt

          # Get all data to boletim3.txt
          awk '{gsub(/<[^>]*>/,"")}1' boletim2.txt >> boletim_final.txt

          # Delete last four lines
          sed -i '$ d' boletim_final.txt
          sed -i '$ d' boletim_final.txt
          sed -i '$ d' boletim_final.txt
          sed -i '$ d' boletim_final.txt

          # For any line start with '*' insert blank line before
          sed -i 's/^\*/\n*/g' boletim_final.txt

          # For any line start with '*' remove it and insert ':arrow_right: ' before it
          sed -i 's/^\*/:arrow_right: /g' boletim_final.txt

          # On end of file insert
          # Agradecimentos ao Thierre Madureira de Souza
          # Automação desenvolvida pelo /tisautomation/
          echo "" >> boletim_final.txt
          echo "_Agradecimentos ao Thierre Madureira de Souza pela inspiração_" >> boletim_final.txt
          echo "_Automação desenvolvida por /Enderson Menezes/ e /Elias Júnior/_" >> boletim_final.txt
          echo "_Aprenda a programar em Codaqui.dev_" >> boletim_final.txt
          echo "Fonte: \`https://boletimsec.com.br/boletim-diario-ciberseguranca/\`" >> boletim_final.txt

          echo "SCRIPT_DATA=$(date +'%d/%m/%Y')" >> $GITHUB_ENV
          echo 'SCRIPT_CONTEUDO<<EOF' >> $GITHUB_ENV
          cat boletim_final.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - uses: JasonEtco/create-an-issue@v2
        id: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATA: ${{ env.SCRIPT_DATA }}
        with:
          filename: .github/boletim.md

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.create-issue.outputs.number }}
          reactions: '+1'
          body: |
            ${{ env.SCRIPT_CONTEUDO }}
